# fly.toml app configuration file generated for poe-stock-image-search-summer-moon-4075 on 2024-04-26T14:43:09-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'poe-stock-image-search-summer-moon-4075'
primary_region = 'lax'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'performance-8x'
